"""
Data Retention and Monetization Package.

============================================================
DATA RETENTION & MONETIZATION LAYER
============================================================

PURPOSE:
This module manages data as a strategic asset, not a byproduct.

Key responsibilities:
- Preserve all valuable system data
- Control data lifecycle and storage cost
- Prepare data for future monetization
- Ensure legal, ethical, and operational safety

============================================================
CORE PRINCIPLES
============================================================

1. DATA IS A STRATEGIC ASSET
   Every piece of data generated by the system has potential value.
   Data must be classified, stored, and preserved appropriately.

2. STRICT CATEGORY SEPARATION
   All data falls into one of six categories:
   - Raw Data (news, OHLCV, on-chain, exchange responses)
   - Processed Data (cleaned, normalized, metrics)
   - Derived Scores (sentiment, risk, volatility)
   - Decision Logs (risk, strategy, trade guard)
   - Execution Records (orders, fills, slippage)
   - System Metadata (health, errors, latency)

3. EXPLICIT RETENTION POLICIES
   Every category has defined retention rules:
   - Raw Data: Long-term (2 years)
   - Processed Data: Medium-long term (1 year)
   - Derived Scores: Indefinite (intellectual property)
   - Decision Logs: Indefinite (audit required)
   - Execution Records: Indefinite (compliance)
   - System Metadata: Short-medium term (90 days)

4. COMPLETE DATA LINEAGE
   Every derived data point is traceable to raw inputs.
   Lineage tracks source, processing steps, timestamps,
   and correlation IDs.

5. MONETIZATION READINESS (NOT SELLING)
   Data is prepared for future monetization:
   - No user-identifiable information
   - No exchange API keys
   - No account balances
   - No execution secrets
   - Anonymized and aggregated

6. STRICT ACCESS CONTROL
   - Internal system: full access
   - External access: read-only, logged
   - Exports: logged, restricted categories
   - Historical data: immutable

7. FAILURE ISOLATION
   Data retention failure must NOT stop trading.
   All failures are logged, never silent.

============================================================
USAGE
============================================================

```python
from data_retention import (
    create_data_retention_manager,
    DataCategory,
    DataSubCategory,
)

# Create manager
manager = create_data_retention_manager()

# Store data with classification
record_id = await manager.store(
    data={"symbol": "BTCUSDT", "close": 50000.0},
    source_type="exchange_api",
    source_name="binance",
    symbol="BTCUSDT",
    hint_category=DataCategory.RAW_DATA,
    hint_subcategory=DataSubCategory.MARKET_OHLCV,
)

# Retrieve with access control
data = await manager.retrieve(
    record_id=record_id,
    actor="strategy_module",
    actor_type="system",
)

# Get lineage
lineage = await manager.get_lineage(record_id)

# Prepare for monetization
anonymized, metadata = await manager.prepare_for_monetization(
    record_id=record_id,
    actor="export_service",
)
```

============================================================
"""

# Models
from .models import (
    # Categories
    DataCategory,
    DataSubCategory,
    # Retention
    RetentionPeriod,
    RetentionDuration,
    RetentionPolicy,
    # Storage
    StorageTier,
    StorageTierConfig,
    # Access
    AccessLevel,
    DataSensitivity,
    # Lineage
    DataSource,
    ProcessingStep,
    DataLineage,
    # Records
    DataRecord,
    AuditAction,
    AuditRecord,
    # Monetization
    MonetizationStatus,
    MonetizationMetadata,
    DataProductType,
    DataProductDefinition,
    # Utilities
    generate_record_id,
    generate_correlation_id,
    compute_data_hash,
    create_default_retention_policies,
    create_storage_tier_configs,
)

# Categories
from .categories import (
    ClassificationRule,
    DataClassifier,
    SUBCATEGORY_TO_CATEGORY,
    get_category_for_subcategory,
    create_classifier,
)

# Lineage
from .lineage import (
    LineageBuilder,
    LineageTracker,
    LineageRegistry,
    CorrelationManager,
    create_lineage_builder,
    create_lineage_tracker,
    create_lineage_registry,
    create_correlation_manager,
    build_simple_lineage,
)

# Policies
from .policies import (
    PolicyRegistry,
    RetentionEvaluator,
    RetentionExecutor,
    RetentionScheduler,
    RetentionJob,
    create_policy_registry,
    create_retention_evaluator,
    create_retention_executor,
    create_retention_scheduler,
)

# Storage
from .storage import (
    StorageMetrics,
    StorageSummary,
    TierRouter,
    StorageBackend,
    InMemoryStorageBackend,
    StorageManager,
    DeduplicationManager,
    create_tier_router,
    create_storage_backend,
    create_storage_manager,
    create_deduplication_manager,
)

# Anonymizer
from .anonymizer import (
    DataAnonymizer,
    DataAggregator,
    MonetizationPreparer,
    PIIDetector,
    PROHIBITED_FIELDS,
    create_anonymizer,
    create_aggregator,
    create_monetization_preparer,
    create_pii_detector,
    get_default_product_definitions,
)

# Access Control
from .access_control import (
    AccessPolicy,
    AccessController,
    ExportController,
    ImmutabilityEnforcer,
    AuditLogger,
    create_access_controller,
    create_export_controller,
    create_immutability_enforcer,
    create_audit_logger,
)

# Manager
from .manager import (
    DataRetentionManager,
    FailSafeRetentionWrapper,
    create_data_retention_manager,
    create_fail_safe_retention,
)


__all__ = [
    # Categories
    "DataCategory",
    "DataSubCategory",
    "ClassificationRule",
    "DataClassifier",
    "SUBCATEGORY_TO_CATEGORY",
    "get_category_for_subcategory",
    "create_classifier",
    # Retention
    "RetentionPeriod",
    "RetentionDuration",
    "RetentionPolicy",
    "PolicyRegistry",
    "RetentionEvaluator",
    "RetentionExecutor",
    "RetentionScheduler",
    "RetentionJob",
    "create_policy_registry",
    "create_retention_evaluator",
    "create_retention_executor",
    "create_retention_scheduler",
    "create_default_retention_policies",
    # Storage
    "StorageTier",
    "StorageTierConfig",
    "StorageMetrics",
    "StorageSummary",
    "TierRouter",
    "StorageBackend",
    "InMemoryStorageBackend",
    "StorageManager",
    "DeduplicationManager",
    "create_storage_tier_configs",
    "create_tier_router",
    "create_storage_backend",
    "create_storage_manager",
    "create_deduplication_manager",
    # Lineage
    "DataSource",
    "ProcessingStep",
    "DataLineage",
    "LineageBuilder",
    "LineageTracker",
    "LineageRegistry",
    "CorrelationManager",
    "create_lineage_builder",
    "create_lineage_tracker",
    "create_lineage_registry",
    "create_correlation_manager",
    "build_simple_lineage",
    # Records
    "DataRecord",
    "AuditAction",
    "AuditRecord",
    "generate_record_id",
    "generate_correlation_id",
    "compute_data_hash",
    # Access Control
    "AccessLevel",
    "DataSensitivity",
    "AccessPolicy",
    "AccessController",
    "ExportController",
    "ImmutabilityEnforcer",
    "AuditLogger",
    "create_access_controller",
    "create_export_controller",
    "create_immutability_enforcer",
    "create_audit_logger",
    # Anonymizer
    "DataAnonymizer",
    "DataAggregator",
    "MonetizationPreparer",
    "PIIDetector",
    "PROHIBITED_FIELDS",
    "create_anonymizer",
    "create_aggregator",
    "create_monetization_preparer",
    "create_pii_detector",
    # Monetization
    "MonetizationStatus",
    "MonetizationMetadata",
    "DataProductType",
    "DataProductDefinition",
    "get_default_product_definitions",
    # Manager
    "DataRetentionManager",
    "FailSafeRetentionWrapper",
    "create_data_retention_manager",
    "create_fail_safe_retention",
]


# Version
__version__ = "1.0.0"
